#!/bin/bash
#
# ossec-hids      This shell script takes care of starting and stopping
#                 the OSSEC-HIDS daemon(s).
#
## BEGIN INIT INFO
# Provides:          ossec-hids-client
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts ossec-hids-client
# Description:       Starts ossec-hids-client using start-stop-daemon
### END INIT INFO

# Source function library.
. /lib/lsb/init-functions

# Defines
DESC="the OSSEC HIDS"
NAME="ossec-hids"
PROG="ossec-control"
EXEC="/var/ossec/bin/${PROG}"
LOCK="/var/lock/subsys/${NAME}"
CONF="/etc/ossec-init.conf"

# Check for binaries and configs
[ -x /var/ossec/bin/ossec-control ] && {
  OSSEC=/var/ossec/bin/ossec-control
  SHORT=ossec-hids
}
[ -z "$OSSEC" ] && exit 1
[ -r /etc/ossec-init.conf ] || exit 1

start() {
        # Start daemons.
        echo -n $"Starting $SHORT: "
        #initlog -q -c "$OSSEC start"
        $OSSEC start > /dev/null
        RETVAL=$?

        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$SHORT

        [ $RETVAL -eq 0 ] && success $"$SHORT startup" || failure $"$SHORT startup"
        echo
        return $RETVAL
}

stop() {
        # Stop daemons.
        echo -n $"Shutting down $SHORT: "
        #initlog -q -c "$OSSEC stop"
        $OSSEC stop > /dev/null
        RETVAL=$?

        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$SHORT

        [ $RETVAL -eq 0 ] && success $"$SHORT shutdown" || failure $"$SHORT shutdown"
        echo
        return $RETVAL
}


status() {
        $OSSEC status
}

restart() {
        stop
        sleep 10
        start
}

# This is a special condition used by ASL
reload() {
        # Stop daemons.
        echo -n $"Reloading $SHORT: "
        #initlog -q -c "$OSSEC stop"
        $OSSEC reload > /dev/null
        RETVAL=$?

        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$SHORT

        [ $RETVAL -eq 0 ] && success $"$SHORT reload" || failure $"$SHORT reload"
        echo
        return $RETVAL

        start

}



# See how we were called.
case "$1" in
        start)
          start
          ;;
        stop)
          stop
          ;;
        status)
          status
          ;;
        restart)
          restart
          ;;
        condrestart)
          if [ -e /var/lock/subsys/$SHORT ]; then restart; fi
          ;;
        reload)
          reload
          ;;
        *)
          echo $"Usage: ossec-hids {start|stop|status|restart|condrestart|reload}"
          exit 1
esac

exit $RETVAL
